# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdemandcategory',
            name='demandcategory',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userdemandcategory',
            name='demandtext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
